# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ComponentTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'IQKeyboardManager' #iOS13 and later
  pod 'SnapKit', '~> 5.7.0'
end
